export default {
  TOPIC_BY_ID_SUCCESS: "TOPIC_BY_ID_SUCCESS",
  ADD_TOPIC_SUCCESS: "ADD_TOPIC_SUCCESS",
  TOPIC_REQUEST: "TOPIC_REQUEST",
  TOPIC_SUCCESS: "TOPIC_SUCCESS",
  TOPIC_FAILURE: "TOPIC_FAILURE",

  MESSAGE_REQUEST: "MESSAGE_REQUEST",
  ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS",
  MESSAGE_FAILURE: "MESSAGE_FAILURE",

  REPLY_REQUEST: "REPLY_REQUEST",
  ADD_REPLY_SUCCESS: "REPLY_SUCCESS",
  REPLY_FAILURE: "REPLY_FAILURE",

};
