export default {
  ADD_TOPIC_SUCCESS: "ADD_TOPIC_SUCCESS",
  TOPIC_REQUEST: "TOPIC_REQUEST",
  TOPIC_SUCCESS: "TOPIC_SUCCESS",
  TOPIC_FAILURE: "TOPIC_FAILURE",

  MESSAGE_REQUEST: "MESSAGE_REQUEST",
  MESSAGE_SUCCESS: "MESSAGE_SUCCESS",
  MESSAGE_FAILURE: "MESSAGE_FAILURE",

  REPLY_REQUEST: "REPLY_REQUEST",
  REPLY_SUCCESS: "REPLY_SUCCESS",
  REPLY_FAILURE: "REPLY_FAILURE",

};
